apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamilton-ventilator-deployment
spec:
  replicas: 3 # Startet 3 Kopien deines Simulators
  selector:
    matchLabels:
      app: ventilator
  template:
    metadata:
      labels:
        app: ventilator
    spec:
      containers:
      - name: ventilator-v1
        image: ghcr.io/benmclemor/hamilton:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
