apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ventilator-ingress
  annotations:
    # Wichtig: Sagt Nginx, wie er mit dem Traffic umgehen soll
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: ventilator.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ventilator-service
            port:
              number: 80
