apiVersion: v1
kind: Service
metadata:
  name: ventilator-service
spec:
  selector:
    app: ventilator
  ports:
    - protocol: TCP
      port: 80 # Erreichbar auf Port 80
      targetPort: 8080
  type: LoadBalancer # Macht es Ã¼ber das Internet/Netzwerk erreichbar
